import type { AnalyticsIntent, PositionBucketKey } from "@/lib/analytics/types";

export const ORGANIC_RESEARCH_HREF = "/analytics/organic/overview/";
export const BACKLINKS_HREF = "/analytics/backlinks/overview/";
export const COMPARE_DOMAINS_HREF = "/analytics/comparedomains/";
export const AI_VISIBILITY_HREF = "/ai-seo/overview/";
export const OVERVIEW_HREF = "/analytics/overview/";
export const SEO_HOME_HREF = "/seo/";

/** 도메인 개요에서 전환 가능한 데이터베이스(국가) — 수집 파이프라인이 지원하는 국가만. */
export const SUPPORTED_COUNTRIES = ["KR", "US"] as const;

export const POSITION_BUCKET_COLORS: Record<PositionBucketKey, string> = {
  "1-3": "#008ff8",
  "4-10": "#12b5a5",
  "11-20": "#8649e1",
  "21-50": "#e0447c",
  "51-100": "#b794f6",
};

export const FEATURE_LABELS: Record<string, { en: string; ko: string }> = {
  featured_snippet: { en: "Featured snippet", ko: "추천 스니펫" },
  people_also_ask: { en: "People also ask", ko: "관련 질문" },
  ai_overview: { en: "AI Overview", ko: "AI 개요" },
  knowledge_panel: { en: "Knowledge panel", ko: "지식 패널" },
  answer_box: { en: "Answer box", ko: "답변 박스" },
  local_pack: { en: "Local pack", ko: "로컬 팩" },
  image_pack: { en: "Image pack", ko: "이미지 팩" },
  video: { en: "Video", ko: "동영상" },
  reviews: { en: "Reviews", ko: "리뷰" },
  top_stories: { en: "Top stories", ko: "주요 뉴스" },
};

/** 의도 배지 표기 — SEMrush 식 원문자(I/N/C/T) + 색상. */
export const INTENT_META: Record<
  AnalyticsIntent,
  { short: string; color: string; bg: string; label: { en: string; ko: string } }
> = {
  informational: {
    short: "I",
    color: "#1e6bd6",
    bg: "#e8f1fd",
    label: { en: "Informational", ko: "정보제공" },
  },
  navigational: {
    short: "N",
    color: "#6d28d9",
    bg: "#f1e9fd",
    label: { en: "Navigational", ko: "탐색" },
  },
  commercial: {
    short: "C",
    color: "#9a7300",
    bg: "#fdf3d8",
    label: { en: "Commercial", ko: "상업" },
  },
  transactional: {
    short: "T",
    color: "#0a7c5c",
    bg: "#e5f7f0",
    label: { en: "Transactional", ko: "거래" },
  },
};

export const COPY = {
  en: {
    // 랜딩
    title: "Domain Overview",
    landingSubtitle: "Get instant insights into the strengths and weaknesses of competitors and prospects.",
    domainPlaceholder: "Enter domain, subdomain or URL",
    searchAction: "Search",
    countryAuto: "Auto (by domain)",
    lastChecked: "Last checked:",
    landingFeatureTitle: "Detailed analysis",
    landingFeatureBullets: [
      "See a domain's information and online visibility at a glance",
      "Analyze a domain's growth trend over time",
      "Identify the markets where a domain stands out",
      "Find the topics and keywords that bring organic search traffic to a domain",
    ],
    landingPrincipleTitle: "Data principles",
    landingPrincipleBody:
      "Every metric is computed only from data this workspace actually collected (TalorData SERP, site-audit crawls). Metrics without a connected source are honestly marked as unavailable instead of showing made-up numbers.",
    availableDomainsTitle: "Domains with collected data",
    availableDomainsMore: "+",
    // 리포트 헤더
    breadcrumbSeo: "SEO",
    domain: "Domain",
    country: "Database",
    device: "Device",
    desktop: "Desktop",
    mobile: "Mobile",
    analyze: "Analyze",
    analyzing: "Analyzing…",
    openSite: "Open site",
    export: "Export JSON",
    liveData: "Live collected data",
    unavailable: "No collected data",
    dataUpdated: "Data updated",
    // 공통
    liveTag: "Live",
    calcTag: "Modeled",
    viewDetails: "View details",
    vsPreviousMonth: "vs previous month",
    noData: "No data available",
    loadError: "The report could not be loaded.",
    initialLoading: "Building the report from source stores…",
    today: "today",
    dayAgo: "1 day ago",
    daysAgo: "days ago",
    // 탭
    overview: "Overview",
    topKeywords: "Top Keywords",
    dataSources: "Data sources",
    compareDomains: "Compare domains",
    // KPI 패널
    aiSearchTag: "AI Search",
    seoTag: "SEO",
    aiVisibilityStat: "AI Visibility",
    mentionsStat: "Mentions",
    citedPagesStat: "Cited pages",
    aiPanelEmpty: "No AI visibility data has been collected for this domain yet.",
    aiPanelHint: "Collect queries in the AI Visibility tool to populate this panel with measured data.",
    openAiVisibility: "Open AI Visibility",
    authority: "Authority Score",
    organicTrafficStat: "Organic Traffic",
    paidTrafficStat: "Paid Traffic",
    referringDomainsStat: "Referring Domains",
    trafficShareStat: "Traffic Share",
    organicKeywordsStat: "Organic Keywords",
    paidKeywordsStat: "Paid Keywords",
    backlinks: "Backlinks",
    unavailableAuthority: "Provided after a backlink crawler source is connected.",
    unavailableVolume: "Provided after a search-volume source is connected.",
    unavailableLinks: "Provided after a link-graph source is connected.",
    unavailablePaid: "Provided after ad SERPs are collected.",
    unavailableShare: "Provided after a clickstream or search-volume source is connected.",
    // 추이 영역
    traffic: "Traffic",
    keywords: "Keywords",
    serpFeaturesTitle: "SERP Features",
    serpFeaturesBasis: "Keywords where the feature appears on the SERP",
    serpFeaturesEmpty: "No SERP features were observed for this scope.",
    // 자연검색 리서치
    organicResearch: "Organic Research",
    topOrganicKeywords: "Top Organic Keywords",
    keyword: "Keyword",
    intentHeader: "Intent",
    position: "Pos.",
    noKeywords: "No top-10 keywords were found for this scope.",
    tableUnavailableNote: "Volume, KD %, CPC and traffic metrics are hidden — no connected data source.",
    keywordsByIntent: "Keywords by Intent",
    intentModelNote: "Rule-based classification (clone-intent-v1), not a measured value.",
    shareHeader: "Share",
    keywordsHeader: "Keywords",
    organicPositionDist: "Organic Position Distribution",
    serpPositionAxis: "Google SERP position",
    currentSnapshot: "Current snapshot",
    topCompetitors: "Main Organic Competitors",
    positioningMap: "Competitive Positioning Map",
    unavailableCompetitors: "Provided once cross-domain SERP aggregation is computed from collected snapshots.",
    // 광고 리서치
    advertising: "Advertising Research",
    topPaidKeywords: "Top Paid Keywords",
    paidPositionDist: "Paid Position Distribution",
    topPaidCompetitors: "Main Paid Competitors",
    sampleAds: "Sample Text Ads",
    paidNoData: "Ad SERP positions are not collected in this workspace yet, so paid search cannot be estimated.",
    // 백링크
    followVsNofollow: "Follow vs Nofollow",
    followLinks: "Follow links",
    nofollowLinks: "Nofollow links",
    refByAuthority: "Referring Domains by Authority Score",
    topAnchors: "Top anchors",
    anchorsNoData: "The link graph does not store anchor text, so anchors cannot be aggregated.",
    topPages: "Top pages",
    host: "Host",
    referringDomainsShort: "Ref. domains",
    // 데이터 원천 탭
    pipelineTitle: "Source-to-metric pipeline",
    pipelineDescription: "Raw identifiers stay on the server. This screen receives only aggregates and modeled results.",
    sourceStores: "Source stores",
    records: "records",
    cadence: "Cadence",
    role: "Used for",
    freshness: "Latest data",
    privacy: "Privacy boundary",
    privacyBody: "Session and user hashes, source network keys, and raw page paths are never returned by the analytics API.",
    // 실시간 수집
    liveCollectTitle: "Collect live SERP data",
    liveCollectDescription: "This domain is not in the local source stores yet. Collect real Google results for its brand keywords (comma-separated; leave empty to use suggestions), then the report is rebuilt from the collected data.",
    liveCollectKeywordsLabel: "Keywords to collect",
    liveCollectPlaceholder: "e.g. brand name, brand service",
    liveCollectAction: "Collect & rebuild report",
    liveCollecting: "Collecting live…",
    liveCollectRanked: "Found at",
    liveCollectNotFound: "Not in top results",
  },
  ko: {
    // 랜딩
    title: "도메인 개요",
    landingSubtitle: "경쟁자와 잠재 고객의 강점 및 약점에 대한 인사이트를 즉시 확보하세요.",
    domainPlaceholder: "도메인, 서브도메인 또는 URL 입력",
    searchAction: "검색",
    countryAuto: "자동 (도메인 기준)",
    lastChecked: "마지막 확인:",
    landingFeatureTitle: "자세한 분석 제공",
    landingFeatureBullets: [
      "도메인의 정보와 온라인 가시성을 한눈에 확인",
      "시간 경과에 따른 도메인의 성장 추세 분석",
      "도메인이 두각을 나타내는 시장 파악",
      "도메인에 자연 검색 트래픽이 유입되는 주제와 키워드 파악",
    ],
    landingPrincipleTitle: "데이터 원칙",
    landingPrincipleBody:
      "모든 지표는 이 워크스페이스가 실제로 수집한 데이터(TalorData SERP, 사이트 진단 크롤)로만 계산합니다. 소스가 없는 지표는 가짜 숫자 대신 미제공으로 정직하게 표시합니다.",
    availableDomainsTitle: "데이터 보유 도메인",
    availableDomainsMore: "+",
    // 리포트 헤더
    breadcrumbSeo: "SEO",
    domain: "도메인",
    country: "데이터베이스",
    device: "기기",
    desktop: "데스크톱",
    mobile: "모바일",
    analyze: "분석",
    analyzing: "분석 중…",
    openSite: "사이트 열기",
    export: "JSON 내보내기",
    liveData: "실시간 수집 데이터",
    unavailable: "수집 데이터 없음",
    dataUpdated: "데이터 갱신",
    // 공통
    liveTag: "실시간",
    calcTag: "계산식",
    viewDetails: "자세히 보기",
    vsPreviousMonth: "이전 달 대비",
    noData: "데이터 없음",
    loadError: "리포트를 불러오지 못했습니다.",
    initialLoading: "원천 스토어에서 리포트를 계산하고 있습니다…",
    today: "오늘",
    dayAgo: "1일 전",
    daysAgo: "일 전",
    // 탭
    overview: "개요",
    topKeywords: "상위 키워드",
    dataSources: "데이터 원천",
    compareDomains: "도메인 비교",
    // KPI 패널
    aiSearchTag: "AI 검색",
    seoTag: "SEO",
    aiVisibilityStat: "AI 가시성",
    mentionsStat: "언급",
    citedPagesStat: "인용된 페이지",
    aiPanelEmpty: "이 도메인의 AI 가시성 수집 데이터가 아직 없습니다.",
    aiPanelHint: "AI 가시성 도구에서 쿼리를 수집하면 실측 데이터가 표시됩니다.",
    openAiVisibility: "AI 가시성 열기",
    authority: "Authority Score",
    organicTrafficStat: "자연 트래픽",
    paidTrafficStat: "유료 트래픽",
    referringDomainsStat: "추천 도메인",
    trafficShareStat: "트래픽 공유",
    organicKeywordsStat: "자연 키워드",
    paidKeywordsStat: "유료 키워드",
    backlinks: "백링크",
    unavailableAuthority: "백링크 크롤러 소스를 연결하면 제공됩니다.",
    unavailableVolume: "검색량 소스를 연결하면 제공됩니다.",
    unavailableLinks: "링크 그래프 소스를 연결하면 제공됩니다.",
    unavailablePaid: "광고 SERP 를 수집하면 제공됩니다.",
    unavailableShare: "클릭스트림·검색량 소스를 연결하면 제공됩니다.",
    // 추이 영역
    traffic: "트래픽",
    keywords: "키워드",
    serpFeaturesTitle: "SERP 피처",
    serpFeaturesBasis: "해당 피처가 나타난 SERP의 키워드 수",
    serpFeaturesEmpty: "이 조건에서 관찰된 SERP 피처가 없습니다.",
    // 자연검색 리서치
    organicResearch: "자연검색 리서치",
    topOrganicKeywords: "상위 자연 키워드",
    keyword: "키워드",
    intentHeader: "의도",
    position: "포지션",
    noKeywords: "이 조건에서 상위 10위 키워드를 찾지 못했습니다.",
    tableUnavailableNote: "검색량·KD·CPC·트래픽 지표는 연결된 데이터 소스가 없어 표시하지 않습니다.",
    keywordsByIntent: "의도별 키워드",
    intentModelNote: "규칙 기반 분류(clone-intent-v1) 결과이며 실측값이 아닙니다.",
    shareHeader: "점유율",
    keywordsHeader: "키워드",
    organicPositionDist: "자연 포지션 분포",
    serpPositionAxis: "Google SERP 포지션",
    currentSnapshot: "현재 스냅샷 기준",
    topCompetitors: "주요 자연 경쟁자",
    positioningMap: "경쟁 포지셔닝 지도",
    unavailableCompetitors: "수집된 SERP 스냅샷의 도메인 교차 집계가 준비되면 제공됩니다.",
    // 광고 리서치
    advertising: "광고 리서치",
    topPaidKeywords: "상위 유료 키워드",
    paidPositionDist: "유료 포지션 분포",
    topPaidCompetitors: "주요 유료 경쟁자",
    sampleAds: "샘플 텍스트 광고",
    paidNoData: "이 워크스페이스는 광고 SERP를 아직 수집하지 않아 유료 검색을 추정할 수 없습니다.",
    // 백링크
    followVsNofollow: "Follow vs Nofollow",
    followLinks: "Follow 링크",
    nofollowLinks: "Nofollow 링크",
    refByAuthority: "Authority Score별 추천 도메인",
    topAnchors: "상위 앵커",
    anchorsNoData: "링크 그래프가 앵커 텍스트를 저장하지 않아 집계할 수 없습니다.",
    topPages: "상위 페이지",
    host: "호스트",
    referringDomainsShort: "추천 도메인",
    // 데이터 원천 탭
    pipelineTitle: "원천 → 지표 계산 파이프라인",
    pipelineDescription: "원시 식별자는 서버에만 남고, 화면에는 집계값과 모델 결과만 전달됩니다.",
    sourceStores: "원천 스토어",
    records: "개 레코드",
    cadence: "갱신",
    role: "사용 목적",
    freshness: "최신 데이터",
    privacy: "개인정보 경계",
    privacyBody: "세션·사용자 해시, 원천 네트워크 키, 원시 페이지 경로는 분석 API 응답에 포함하지 않습니다.",
    // 실시간 수집
    liveCollectTitle: "실시간 SERP 수집",
    liveCollectDescription: "로컬 원천 스토어에 없는 도메인입니다. 브랜드 키워드의 실제 Google 결과를 수집하면(쉼표 구분, 비우면 추천 키워드 사용) 수집 데이터로 리포트를 다시 계산합니다.",
    liveCollectKeywordsLabel: "수집할 키워드",
    liveCollectPlaceholder: "예: 브랜드명, 브랜드 서비스",
    liveCollectAction: "수집 후 리포트 생성",
    liveCollecting: "실시간 수집 중…",
    liveCollectRanked: "순위 확인됨",
    liveCollectNotFound: "상위 결과에 없음",
  },
} as const;

export type Copy = (typeof COPY)[keyof typeof COPY];
